apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    name: production
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-node
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.1
          ports:
          - containerPort: 80          
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 600Mi
              cpu: 600m


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 80
    nodePort: 30163
    protocol: TCP
    name: http
  selector:
    type: front-node
    app: nginx-app
