apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    name: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-app-front
  template:
    metadata:
      name: nginx-pod
kind: Deployment
metadata:
  name: deploy
  labels:
    name: production
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-app-front
  template:
    metadata:
      name: nginx-pod

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    name: dev-prod
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-app-front
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-node
        app: nginx-app-front
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.1
          ports:
          - containerPort: 80
